# Generated by Django 5.0.6 on 2024-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='ad_login',
        ),
    ]
