# Generated by Django 5.0.6 on 2024-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_ad_login_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='media/')),
                ('place', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=30)),
                ('person', models.CharField(max_length=30)),
                ('explor', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
