# Generated by Django 5.0.6 on 2024-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='person',
            field=models.IntegerField(),
        ),
    ]
