# Generated by Django 5.0.6 on 2024-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_package_days_alter_package_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(default='family tour', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
