# Generated by Django 5.0.6 on 2024-05-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_package_type_alter_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='pack',
            fields=[
                ('pack_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(default='Family', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
        migrations.AddField(
            model_name='package',
            name='pack_name',
            field=models.ForeignKey(default='Family', on_delete=django.db.models.deletion.CASCADE, to='myapp.pack'),
        ),
    ]
