# Generated by Django 5.0.6 on 2024-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pack_remove_package_type_package_pack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='pack_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
