# Generated by Django 5.0.6 on 2024-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pack_pack_id_alter_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='pack_name',
            field=models.CharField(max_length=200),
        ),
    ]
