# Generated by Django 5.0.6 on 2024-05-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pack1_remove_package_pack_name_package2_delete_pack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package2',
            name='pack',
        ),
        migrations.DeleteModel(
            name='pack1',
        ),
    ]
