# Generated by Django 5.0.6 on 2024-05-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_pack1_package_delete_package2'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='tour_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tour'),
        ),
        migrations.DeleteModel(
            name='pack1',
        ),
    ]
